name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build Appimage on Ubuntu"
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - run: sudo apt update

      - name: Install meson
        run: sudo apt install meson
        
      - name: Install dependencies
        run: sudo apt install libsfml-dev libboost-program-options-dev
        
      - name: Configure the project with meson
        run: meson build -Dprefix=$(pwd)/AppDir/usr
        
      - name: Compile and install to AppDir
        run: ninja -vC build install

      - name: Download linuxdeploy
        run: wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage && chmod +x linuxdeploy-x86_64.AppImage

      - name: Create AppDir
        run: ./linuxdeploy-x86_64.AppImage --appdir AppDir

      - name: Create AppImage
        run: ./linuxdeploy-x86_64.AppImage --appdir AppDir --output appimage

      - name: Save AppImage
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: Game_of_life*
